### PR TITLE
fix: recover macos functionality

### PR DESCRIPTION
**Pull request by ewann**
👋 

This PR recovers macOS testing functionality, which I last saw working in 3.10.0. Since then it appears to fail with:

```
.pub-cache/hosted/pub.dev/patrol-3.12.0/darwin/Classes/AutomatorServer/Automator/MacOSAutomator.swift:6:9: error: type 'MacOSAutomator' does not conform to protocol 'Automator'
	  class MacOSAutomator: Automator {
	        ^
```

this still seems an issue at commit:  6a1df028d0a4e525451b43eaf160634d6161c988

Testing:
works on my machine. I didn't quickly find a test suite to run / update locally, though at a guess there is some coverage missing for this functionality / platform. Let me know if there are other things I can do to help with this submission.

### CODE REVIEW

**Review by mateuszwojtczak — APPROVED** [review]
LGTM, thanks for your contribution

**Comment by mateuszwojtczak** [comment]
Also, please update the changelog

**Review by pdenert — APPROVED** [review]
lgtm
