### ISSUE TITLE
patrol_cli 4.4.0:  silent fail when `patrol:` block is missing in pubspec.yaml

### ISSUE THREAD

**Issue by hardy716** [leancodepl/patrol#3102]
### Steps to reproduce

  Using the patrol monorepo's own example app:
  
  ```bash 
  git clone https://github.com/leancodepl/patrol
  cd patrol/packages/patrol/example
  # Edit pubspec.yaml — remove the entire `patrol:` block
  patrol test --target integration_test/example_test.dart --device "<any iOS sim>"
  ```
  
  **Expected**: CLI prints a clear warning that the `patrol:` block is missing and `bundle_id` will be empty.

### Actual results

  - ✅ patrol build succeeds
  - ✅ app installs on the simulator
  - ❌ every scenario fails with no obvious cause; the CLI summary shows `Total: N / Successful: 0 / Failed: 0` (silent because no result
  ever comes back from the native side)
  
  The CLI proceeds without any warning. Because `PubspecReader.read()` returns an empty config when `pubspec.yaml` has no `patrol:` block,
  the native runner queries the OS for an app with an empty `bundle_id`, producing the error shown in Logs below.
  
  Note the **two spaces** between `Application` and `is`: it's the concatenation `'Application ' + '' + ' is not running'` with the empty
  bundle id. For first-time Patrol users this is extremely hard to diagnose — the actual root cause is only visible after extracting the
  xcresult bundle's log ref.

### Logs

xcresult bundle log ref (relevant portion):

```
PatrolServer: INFO: App reported that it is ready
[connection] nw_socket_handle_socket_event ... Socket SO_ERROR [61: Connection refused]
PatrolServer: INFO: tapping on view with text 'Allow' in app
PatrolServer: INFO: waiting for existence of view with text 'Allow' in app
RunnerUITests.m:5: error: -[RunnerUITests <scenario>] : Failed to resolve query: Application  is not running
PatrolServer: ERROR: view with text 'Allow' in app  doesn't exist
```

  Both `'Allow' in app ` (trailing space + empty) and `Application  is not running` (double space) reveal the empty `bundle_id`
  concatenation.
  
  The affected code path in `packages/patrol_cli/lib/src/pubspec_reader.dart`:

code:

```dart
final patrol = yaml['patrol'] as Map?;
if (patrol == null) {
  return config;
}
```

was introduced in #892 (2023-02-07) and is unchanged on `master` (verified via `git blame`). Likely affects all releases since
  **patrol_cli 2.6.x onward (2.x / 3.x / 4.x)**.

### Patrol version

  - patrol_cli: ^4.4.0
  - patrol: ^4.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
$ patrol doctor
Patrol doctor:
Patrol CLI version: 4.4.0
Flutter command: flutter 
  Flutter 3.41.8 • channel stable
Android: 
• Program adb not found (install with `export PATH="$ANDROID_HOME/platform-tools:$PATH"`)
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Web: 
• Program node found in /usr/local/bin/node
• Program npm found in /usr/local/bin/npm
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.41.8, on macOS 26.3.1 25D771280a darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.2)
[✓] Chrome - develop for the web
[✓] Connected device (4 available)
[✓] Network resources
  
• No issues found!
```

</details>
