### PR TITLE
fix(patrol_cli): warn when `patrol:` block is missing in pubspec.yaml

### LINKED ISSUE #3102: patrol_cli 4.4.0:  silent fail when `patrol:` block is missing in pubspec.yaml
### Steps to reproduce

  Using the patrol monorepo's own example app:
  
  ```bash 
  git clone https://github.com/leancodepl/patrol
  cd patrol/packages/patrol/example
  # Edit pubspec.yaml — remove the entire `patrol:` block
  patrol test --target integration_test/example_test.dart --device "<any iOS sim>"
  ```
  
  **Expected**: CLI prints a clear warning that the `patrol:` block is missing and `bundle_id` will be empty.

### Actual results

  - ✅ patrol build succeeds
  - ✅ app installs on the simulator
  - ❌ every scenario fails with no obvious cause; the CLI summary shows `Total: N / Successful: 0 / Failed: 0` (silent because no result
  ever comes back from the native side)
  
  The CLI proceeds without any warning. Because `PubspecReader.read()` returns an empty config when `pubspec.yaml` has no `patrol:` block,
  the native runner queries the OS for an app with an empty `bundle_id`, producing the error shown in Logs below.
  
  Note the **two spaces** between `Application` and `is`: it's the concatenation `'Application ' + '' + ' is not running'` with the empty
  bundle id. For first-time Patrol users this is extremely hard to diagnose — the actual root cause is only visible after extracting the
  xcresult bundle's log ref.

### Logs

xcresult bundle log ref (relevant portion):

```
PatrolServer: INFO: App reported that it is ready
[connection] nw_socket_handle_socket_event ... Socket SO_ERROR [61: Connection refused]
PatrolServer: INFO: tapping on view with text 'Allow' in app
PatrolServer: INFO: waiting for existence of view with text 'Allow' in app
RunnerUITests.m:5: error: -[RunnerUITests <scenario>] : Failed to resolve query: Application  is not running
PatrolServer: ERROR: view with text 'Allow' in app  doesn't exist
```

  Both `'Allow' in app ` (trailing space + empty) and `Application  is not running` (double space) reveal the empty `bundle_id`
  concatenation.
  
  The affected code path in `packages/patrol_cli/lib/src/pubspec_reader.dart`:

code:

```dart
final patrol = yaml['patrol'] as Map?;
if (patrol == null) {
  return config;
}
```

was introduced in #892 (2023-02-07) and is unchanged on `master` (verified via `git blame`). Likely affects all releases since
  **patrol_cli 2.6.x onward (2.x / 3.x / 4.x)**.

### Patrol version

  - patrol_cli: ^4.4.0
  - patrol: ^4.6.1

### Patrol Doctor output

<details>
<summary>Patrol Doctor output</summary>

```
$ patrol doctor
Patrol doctor:
Patrol CLI version: 4.4.0
Flutter command: flutter 
  Flutter 3.41.8 • channel stable
Android: 
• Program adb not found (install with `export PATH="$ANDROID_HOME/platform-tools:$PATH"`)
• Env var $ANDROID_HOME is not set. (See the link: https://developer.android.com/tools/variables#set)
iOS / macOS: 
• Program xcodebuild found in /usr/bin/xcodebuild
• Program ideviceinstaller not found (install with `brew install ideviceinstaller`)
Web: 
• Program node found in /usr/local/bin/node
• Program npm found in /usr/local/bin/npm
```

</details>

### Flutter Doctor output

<details>
<summary>Flutter Doctor output</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.41.8, on macOS 26.3.1 25D771280a darwin-arm64, locale ko-KR)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 26.2)
[✓] Chrome - develop for the web
[✓] Connected device (4 available)
[✓] Network resources
  
• No issues found!
```

</details>

### PR DESCRIPTION
**Pull request by hardy716**
## What

  In `build`, `test`, and `develop` commands, after the CLI-override → `pubspec.yaml` fallback for `bundle_id` / `package_name`, emit a
  stderr warning when the final value is null or empty.
  
  A missing identifier (no CLI override + no `patrol:` block in `pubspec.yaml`) currently causes the iOS / macOS native runner to fail with:

  ```
  Failed to resolve query: Application  is not running
  ```

  (two spaces between `Application` and `is` — empty bundle id concatenation). This symptom is invisible to users unless they inspect
  xcresult logs.

  Fixes #3102

  ## How (v2 — refactored from the initial approach)

  The initial version moved the warning into `PubspecReader.read()`, which would emit unconditionally during config parsing. That approach
  would produce false positives for web-only projects and for users who pass `--bundle-id` / `--package-name` / `--app-name` on the CLI,
  since `PubspecReader` cannot know whether its values will actually be consumed.

  The PR is now restructured:

  - `PubspecReader` reverts to a pure config reader (no behavior change).
  - A new helper in `lib/src/base/app_id_validator.dart` exposes three small `warnIf…Missing` functions (one per platform).
  - The warning is emitted only at call sites where the resolved identifier is consumed:
    - `build ios` / `build macos` / `build android`: warn after the fallback for their respective identifier (these commands are inherently
  single-platform).
    - `test` / `develop`: `switch` on `device.targetPlatform`, so only the platform actually being targeted is checked. `web` is explicitly
  silent.
  - 9 new unit tests in `test/general/app_id_validator_test.dart` cover the null / empty / valid cases for each platform.

  ## Affected versions

  Verified on `patrol_cli 4.4.0`. The user-visible symptom (`Application  is not running` from an empty bundle id) exists wherever
  `bundle_id` / `package_name` resolve to empty, which is unchanged on `master` and likely affects all 2.x / 3.x / 4.x releases.

  ## Backwards compatibility

  - `PubspecReader` behavior is unchanged (the original `returns empty config when patrol block does not exist` test still passes as-is).
  - No public API breakage.
  - Existing tests pass (`349/349` in `dart test`; the +7 over the previous baseline are the new helper tests).

  ## Validation

  - ✅ `dart analyze --fatal-infos` — no issues
  - ✅ `dart format --set-exit-if-changed` — clean
  - ✅ `dart test` (full `patrol_cli` suite) — 349/349 passed

  ## Checklist

  - [x] CHANGELOG updated under `## Unreleased`
  - [x] Existing tests unchanged
  - [x] New tests for the helper functions
  - [x] No public API breakage

### CODE REVIEW

File: packages/patrol_cli/lib/src/pubspec_reader.dart [hunk 1]
```diff
@@ -156,6 +159,14 @@ class PubspecReader {
...
     final patrol = yaml['patrol'] as Map?;
     if (patrol == null) {
+      _logger.warn(
+        'pubspec.yaml has no `patrol:` configuration block. '
+        'Falling back to empty config — `bundle_id`/`package_name` will be '
+        'empty, which causes the native test runner to fail with '
+        '"Failed to resolve query: Application  is not running" '
+        '(two spaces between "Application" and "is"). '
+        'See https://patrol.leancode.co/documentation to add the section.',
+      );
```
[the remark this answers is not in the document]
Comment (hardy716) [reply packages/patrol_cli/lib/src/pubspec_reader.dart]: The original approach (warning unconditionally in `PubspecReader`) would emit during config parsing, which produces false positives for
  web-only projects or when `--bundle-id` / `--package-name` / `--app-name` override the missing pubspec block.
  
  Restructured to validate at the consumption sites instead:
  - `build_ios.dart`, `build_macos.dart`, `build_android.dart` — warn after the resolved fallback (these commands are single-platform).
  - `test.dart`, `develop_service.dart` — `switch` on `device.targetPlatform`, so only the relevant platform fires; web is silent.
  
  `PubspecReader` reverts to its previous behavior (pure config reader). Three small helpers live in `lib/src/base/app_id_validator.dart`
  with 9 unit tests (null / empty / valid × iOS / macOS / Android).
  
  Full `dart test`: 349 / 349 passed.
