### PR TITLE
[LACKS TESTS] Replace `drag()` with `timedDrag()` in Patrol's scrolling and dragging methods

### PR DESCRIPTION
**Pull request by ehabibov**
Feature: `drag()` in `dragUntilVisible()` replaced with `timedDrag()`

Motivation. Currently `scrollTo`/`scrollUntilVisible` run too fast through activity to target Widget which is not the behaviour users actually act. Having `dragDuration` optional param will allow to slow down scrolling which will bring us closer to it.

Signature will remain the same so API is not got broken, but now there is a confusion with first param - `duration` in relation to new `scrollDuration` which is actually a timeout. But changing that will break API.
`await $(#loc).scrollTo(duration: const Duration(seconds: 1), scrollDuration: const Duration(seconds: 1));`

Just a note: I tested it in my project over cloned 1.0.8 referring to local patrol repo, but I could not build (and test) it on forked 1.0.9 as faced kotlin compile issues and could not solve it due to lack of flutter/dart knowledge/exp:

<details>
  <summary>log</summary>

```
 : > Task :patrol:compileDebugKotlin FAILED
        e: /Users/user/.pub-cache/hosted/pub.dev/patrol-1.0.8/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt: (17, 11): Redeclaration: Empty
        e: /Users/user/.pub-cache/hosted/pub.dev/patrol-1.0.8/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt: (19, 7): Redeclaration: AutomatorServer
        e: /Users/user/.pub-cache/hosted/pub.dev/patrol-1.0.8/android/src/main/kotlin/pl/leancode/patrol/PatrolPlugin.kt: (9, 7): Redeclaration: PatrolPlugin
        e: /Users/user/.pub-cache/hosted/pub.dev/patrol-1.0.8/android/src/main/kotlin/pl/leancode/patrol/PatrolServer.kt: (8, 7): Redeclaration: PatrolServer
        e: /Users/user/.pub-cache/hosted/pub.dev/patrol-1.0.8/android/src/main/kotlin/pl/leancode/patrol/PatrolTestRunner.kt: (5, 7): Redeclaration: PatrolTestRunner
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt: (17, 11): Redeclaration: Empty
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/AutomatorServer.kt: (19, 7): Redeclaration: AutomatorServer
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolPlugin.kt: (9, 7): Redeclaration: PatrolPlugin
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolServer.kt: (9, 7): Redeclaration: PatrolServer
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolServer.kt: (21, 21): Cannot find a parameter with this name: automation
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolServer.kt: (22, 21): Cannot find a parameter with this name: onTestResultsSubmitted
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolServer.kt: (22, 71): Unresolved reference: it
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolTestRunner.kt: (13, 7): Redeclaration: PatrolTestRunner
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolTestRunner.kt: (62, 26): Unresolved reference: testResults
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolTestRunner.kt: (71, 30): Unresolved reference: keys
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolTestRunner.kt: (75, 17): Operator '!=' cannot be applied to 'MatchGroup?' and 'String'
        e: /Users/user/patrol/packages/patrol/android/src/main/kotlin/pl/leancode/patrol/PatrolTestRunner.kt: (76, 38): None of the following functions can be called with the arguments supplied: 
        public final fun <init>(p0: String!): kotlin.Exception /* = java.lang.Exception */ defined in kotlin.Exception
        public final fun <init>(p0: Throwable!): kotlin.Exception /* = java.lang.Exception */ defined in kotlin.Exception
        
        FAILURE: Build completed with 2 failures.
        
        1: Task failed with an exception.
        -----------
        * What went wrong:
        Execution failed for task ':patrol:compileDebugKotlin'.
        > Compilation error. See log for more details
```

</details>

### CODE REVIEW

**Comment by bartekpacia** [comment]
Hi, thanks a lot for contributing! :)

Actually, LeanCode's QA team reported (what seems like) the same exact bug just yesterday, and I planned to create an issue to track it (and fix it soon™). But now you've submitted a PR that already targets it - awesome! :)

> I tested it in my project over cloned 1.0.8 referring to local patrol repo, but I could not build (and test) it on forked 1.0.9 as faced kotlin compile issues and could not solve it due to lack of flutter/dart knowledge/exp:

Ah yes, we also experienced this problem when updating from 1.0.8 to 1.0.9 (and it wasn't the first time it occurred). I'm pretty sure it's some elusive bug related to pub.dev and/or Gradle using outdated caches of Flutter plugins' native code. 

The workaround that has so far worked 100% of the time is to:

```console
dart pub cache clean
# or alternatively:
rm -rf ~/.pub-cache
```

and then (in the _app_'s `android` directory):

```console
./gradlew :clean
```

---

One more thing that I'd like to see in this PR is tests to ensure this new functionality works. In other words, a test that:
- fails without changes made in this PR
- succeeds with changes made in this PR

Are you up to doing it as well? :)

**Comment by ehabibov** [comment]
Hey!

Just to be clear:
1. This PR just about enhancing (as I see it) scroll function.
2. Build issue is just secondary thing I which did not allow me to test new scrolls on 1.0.9 (but I don't think something changed since 1.0.8 there).

Tests:
I could not imagine how test should be look like as change just allows to do same scroll but slowed down by setting scroll duration to its every single action. Btw, there might be test impl problems, as I'm in dart/flutter (and integration_test) 2-3 weeks and building widgets for test could be a problem for me.

**Comment by bartekpacia** [comment]
> This PR just about enhancing (as I see it) scroll function.

Yeah, understood. I was just saying that we also experienced the same problem as you :)

> Build issue is just secondary thing I which did not allow me to test new scrolls on 1.0.9 (but I don't think something changed since 1.0.8 there).

Yup. I just wanted to let you know how we solved it so you (and other future readers) will also know how to deal with this problem.

As for the test - sure, no problem. I'll write them.

**Comment by bartekpacia** [comment]
@jBorkowska Is this issue not relevant anymore in Patrol 2.0?

**Comment by jBorkowska** [comment]
@bartekpacia it would be nice to check if the original problem is solved, bc we did more than replace `drag()` with `timedDrag()`

**Comment by jBorkowska** [comment]
Closing, bc this changes are included in Patrol 2.0
